# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormtech_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
