# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('author', models.CharField(default='', max_length=256)),
                ('year', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
